### ISSUE TITLE
Any chance making SX1280 chip compatible?

### ISSUE THREAD

**Issue by happytm** [deulis/ESP32_Codec2#1]
Great project.

I would like to test some modules from Ebyte based on Semtech SX1280 chip. There is library supporting this chip at https://github.com/StuartsProjects/SX12XX-LoRa.

Is it possible to use above library with your project ? If so what are the changes required in code ?

Thanks.

**Comment by deulis** [comment]
I am sorry for my delayed answer, just now I see your question. I only test it on TTGO module.  I guess you can use any Lora Module. Actually the library  that I am using to transmit and receive LoRa is not from me. My work here is to run the codec2 on the ESP32, to transmit the frames you can use any other thing, in this case I am using LoRa.

**Comment by happytm** [comment]
Thank you for your response.

I think following library covers most of the chips (SX126x, SX127x and SX128x) and it is very simple to implement:

https://github.com/StuartsProjects/SX12XX-LoRa

It would be nice to have support for new SX1262, SX1268 and SX1280 chips from Semtech with above library. All these new chips have benefits over SX1276 or SX1278 either as a better range, low power consumption or 100 % duty cycle in case of SX1280. The library you used does not support new chips mentioned.

Thanks.

**Comment by deulis** [comment]
OK, let me know if it works with this other LoRa library. By the way can I close this issue?
