### ISSUE TITLE
License on this?

### ISSUE THREAD

**Issue by wgaylord** [deulis/ESP32_Codec2#3]
What is the license on your code? (Specifically the .ino since Codec2 is under its open source license.)

**Comment by deulis** [comment]
Hi. 
I didn't think about that because for me it is a simple code just for demonstration, but anyway I need to put the correct license and because the codec2 is already a GNU-GPL licensed, I decided to use the same license. 
Thank you!

**Comment by wgaylord** [comment]
I was asking because I plan on using your .ino as a base to implement a "radio" to allow me to talk on [M17](https://m17project.org/) Reflectors over IP.

**Comment by deulis** [comment]
great to know that!
